debian/tmp/usr/lib/mailman/Mailman      usr/share/mailman
debian/tmp/usr/lib/mailman/bin          usr/share/mailman
debian/tmp/usr/lib/mailman/cron         usr/share/mailman
debian/tmp/usr/lib/mailman/scripts      usr/share/mailman
debian/tmp/usr/lib/mailman/icons/*      usr/share/images/mailman
debian/manpages/*                       usr/share/man/man8
debian/tmp/var/lib/mailman/data         var/lib/mailman


