#!/bin/sh -e
# $URL$
# $Id$

mm_etc=/etc/mailman
mm_tmpl=${mm_etc}/templates

mm_languages="big5 ca cs da de en es et eu fi fr gb hr hu it ja ko lt nl no pl pt pt_BR ro ru sl sr sv uk"

if [ "$1" = "install" ] ; then
  for lang in $(cd ${mm_etc} ; find * -maxdepth 0 -type d); do
    if echo " ${mm_languages} " | grep -q " ${lang} " ; then
      [ -d ${mm_tmpl} ] || mkdir -p ${mm_tmpl}
      mv -f ${mm_etc}/${lang} ${mm_tmpl}
    fi
  done
fi

#DEBHELPER#

exit 0
