#! /bin/sh -e
#
# prerm script for Debian python packages.
# Written 1998 by Gregor Hoffleit <flight@debian.org>.
#
# $URL$
# $Id$

# Hack to allow upgrade from broken 2.1.1 installs where stopping
# mailman will fail.  This hack can be removed after sarge+1 is released.

if [ "$1" = "failed-upgrade" -a \( "$2" = "2.1.1-1" -o \
     "$2" = "2.1.1-2" -o "$2" = "2.1.1-3" \) ]; then
  if [ -x "/etc/init.d/mailman" ]; then
    if [ -x /usr/sbin/invoke-rc.d ] ; then
   	  invoke-rc.d mailman stop || true
    else
      /etc/init.d/mailman stop || true
    fi
  fi
  chmod -x /usr/lib/mailman/bin/mailmanctl
fi

if [ "$1" = "failed-upgrade" ] && dpkg --compare-versions "$2" gt "2.1.4-2" ; then
  if [ -x "/etc/init.d/mailman" ]; then
    if [ -x /usr/sbin/invoke-rc.d ] ; then
      invoke-rc.d mailman stop || true
    else
      /etc/init.d/mailman stop || true
    fi
  fi
  chmod -x /usr/lib/mailman/bin/mailmanctl
fi

#DEBHELPER#

PACKAGE=mailman

# dh_python doesn't do TRT[tm], do it manually
# We have created symlinks and compiled .py files in the postinst, undo now.
dpkg --listfiles $PACKAGE |
	sed -e '/.py$/!d' -e ':^/usr/share/mailman:!d' \
      -e 's:/usr/share\(/mailman/.*)\.py$:/var/lib\1.py\n/var/lib\1.pyc\n/var/lib\1.pyo:' |
	xargs rm -f >&2
